---
- name: Reinstall playbook
  hosts: localhost
  roles:
    - role: systemSetup
    - role: dnfInstall
      when: ansible_facts['os_family'] == "RedHat"
    - role: aptInstall
      when: ansible_facts['os_family'] == "Debian"
    - role: flatpakInstall
    - role: distroboxInstall
