---
- name: reinstall playbook
  hosts: localhost

- hosts: localhost
  become: false
  roles:
  - systemSetup

- hosts: localhost
  become: true
  roles:
  - dnfInstall

- hosts: localhost
  become: false
  roles:
  - flatpakInstall

- hosts: localhost
  become: false
  roles:
  - distroboxInstall

- hosts: localhost
  become: false
  roles:
  - dotfilesSetup