---
- name: Install needed software, that can't run in distrobox
  become: true
  ansible.builtin.apt:
    pkg:
      - ufw
      - gufw
      - timeshift
      - distrobox
      - syncthing
      - i3
      - rofi
      - vim
      - terminator
      - clamav
      - clamav-freshclam
      - flatpak
      - xclip
      - lxpolkit
      # - libreoffice-langpack-da
      - stow
      - pavucontrol
      - volumeicon-alsa
      - blueman
      - htop
      - tealdeer
      - tmux
      - tree
      # - eza # not in debian repo
      # - dua-cli # not in debian repo
      - which
      - feh


- name: Remove preinstalled apps
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - libreoffice
    - libreoffice-common
    - thunderbird
    - vlc
    - gnome-2048
    - gnome-sudoku
    - gnome-robots
    - gnome-nibbles
    - gnome-chess
    - gnome-klotski
    - gnome-mahjongg
    - gnome-mines
    - gnome-taquin
    - gnome-tetravex
    - firefox-esr
    - firefox
    - kmahjongg
    - kmines
    - kpat
    - kmail
    - neochat
    - krdc
    - krfb
    - pim-data-exporter
    - pim-sieve-editor
    - dragon
    - elisa-player

- name: Upgrade all installed packages to latest version
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    autoremove: true
