---
- name: Install needed software, that can't run in distrobox
  become: true
  ansible.builtin.apt:
    pkg:
      - ufw
      - gufw
      - timeshift
      - distrobox
      - syncthing
      - vim
      - terminator
      - clamav
      - clamav-freshclam
      - flatpak
      - lxpolkit
      - stow
      - pavucontrol
      - volumeicon-alsa
      - htop
      - tealdeer
      - tmux
      - tree
      - eza 
      - which
      - feh
      - alacritty
      - curl


- name: Remove preinstalled apps
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - libreoffice
    - libreoffice-common
    - thunderbird
    - vlc
    - gnome-2048
    - gnome-sudoku
    - gnome-robots
    - gnome-nibbles
    - gnome-chess
    - gnome-klotski
    - gnome-mahjongg
    - gnome-mines
    - gnome-taquin
    - gnome-tetravex
    - firefox-esr
    - firefox
    - kmahjongg
    - kmines
    - kpat
    - kmail
    - neochat
    - krdc
    - krfb
    - pim-data-exporter
    - pim-sieve-editor
    - dragonplayer
    - elisa-player
    - akregator
    - dragonplayer
    - juk
    - kaddressbook
    - kaddressbook-data
    - korganizer

- name: Upgrade all installed packages to latest version
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    autoremove: true
