---
- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.github.tchx84.Flatseal
      - com.mattjakeman.ExtensionManager
      - com.spotify.Client
      - md.obsidian.Obsidian
      - org.signal.Signal
      - org.videolan.VLC
      - org.libreoffice.LibreOffice
      - com.rustdesk.RustDesk
      - com.brave.Browser
      - org.remmina.Remmina
      - org.onlyoffice.desktopeditors
    method: user
