---
# inspiration: https://stegosaurusdormant.com/bare-git-repo/
- name: make temp dotfiles folder
  file:
    path: $HOME/dotfiles-tmp
    state: directory
    mode: '0755'

- name: Sync dotfiles
  git:
    repo: https://github.com/Ramiraz80/dotfiles-thor.git
    dest: $HOME/dotfiles-tmp
    separate_git_dir: $HOME/.dotfilesGIT

- name: move dotfiles with rsync
  ansible.builtin.shell:
    cmd: rsync --recursive --verbose --exclude '.git' $HOME/dotfiles-tmp/ $HOME/

- name: deleting temp dir.
  file:
    path: $HOME/dotfiles-tmp
    state: absent

