---
- name: Create distrobox containers
  ansible.builtin.shell:
    cmd: yes | distrobox create -n "{{ item }}" -i fedora:42
  loop:
    - fwsbox
  changed_when: false

- name: Install packages in fwsbox container
  ansible.builtin.shell:
    cmd: distrobox enter fwsbox -- "{{ item }}"
  loop:
    - "sudo dnf install -y htop"
    - "sudo dnf install -y tldr"
    - "sudo dnf install -y tmux"
    - "sudo dnf install -y tree"
    - "sudo dnf install -y which"
  changed_when: false

- name: Export packages in fws38 container
  ansible.builtin.shell:
    cmd: distrobox enter fws38 -- "{{ item }}"
  loop:
    - "distrobox-export -b /usr/bin/htop -ep $HOME/.local/bin"
    - "distrobox-export -b /usr/bin/tldr -ep $HOME/.local/bin"
    - "distrobox-export -b /usr/bin/tmux -ep $HOME/.local/bin"
    - "distrobox-export -b /usr/bin/tree -ep $HOME/.local/bin"
  changed_when: false
