---
# inspiration: https://stegosaurusdormant.com/bare-git-repo/

- name: make temp dotfiles folder
  file:
    path: $HOME/dotfiles-tmp
    state: directory
    mode: '0755'

- name: Get the repository URL
  raw: read -p "Please enter the repository URL:" repository_url

- name: Sync dotfiles
  git:
    repo: "{{ repository_url.stdout }}"
    dest: $HOME/dotfiles-tmp
    separate_git_dir: $HOME/.dotfilesGIT

- name: move dotfiles with rsync
  ansible.builtin.shell:
    cmd: rsync --recursive --verbose --exclude '.git' $HOME/dotfiles-tmp/ $HOME/

- name: deleting temp dir.
  file:
    path: $HOME/dotfiles-tmp
    state: absent

